import { create } from "zustand";

export type VirtualFile = {
  path: string;
  content: string;
};

type StudioState = {
  files: Record<string, VirtualFile>;
  selectedFilePath: string;
  setSelectedFilePath: (path: string) => void;
  upsertFile: (file: VirtualFile) => void;
};

const initialApp = `export default function App() {
  return (
    <main className="min-h-screen bg-slate-950 text-white">
      <section className="mx-auto max-w-4xl px-6 py-24">
        <p className="text-sm text-violet-300">Generated by X09</p>
        <h1 className="mt-4 text-5xl font-bold">Seu app começa aqui.</h1>
      </section>
    </main>
  );
}
`;

export const useStudioStore = create<StudioState>((set) => ({
  files: {
    "/src/App.tsx": {
      path: "/src/App.tsx",
      content: initialApp,
    },
  },
  selectedFilePath: "/src/App.tsx",
  setSelectedFilePath: (path) => set({ selectedFilePath: path }),
  upsertFile: (file) =>
    set((state) => ({
      files: {
        ...state.files,
        [file.path]: file,
      },
      selectedFilePath: file.path,
    })),
}));
