import { create } from "zustand";

export type VirtualFile = {
  path: string;
  content: string;
};

export type ChatMessage = {
  id: string;
  role: "user" | "ai";
  content: string;
};

type StudioState = {
  messages: ChatMessage[];
  isGenerating: boolean;
  files: Record<string, VirtualFile>;
  selectedFilePath: string;
  addMessage: (message: ChatMessage) => void;
  sendMessage: (prompt: string) => Promise<void>;
  setSelectedFilePath: (path: string) => void;
  upsertFile: (file: VirtualFile) => void;
};

const initialApp = `export default function App() {
  return (
    <main className="min-h-screen bg-slate-950 text-white">
      <section className="mx-auto max-w-4xl px-6 py-24">
        <p className="text-sm text-violet-300">Generated by X09</p>
        <h1 className="mt-4 text-5xl font-bold">Seu app começa aqui.</h1>
      </section>
    </main>
  );
}
`;

export const useStudioStore = create<StudioState>((set) => ({
  messages: [
    {
      id: "welcome",
      role: "ai",
      content:
        "Olá, eu sou o X09. Descreva o sistema que você quer construir e eu preparo a primeira versão.",
    },
  ],
  isGenerating: false,
  files: {
    "/src/App.tsx": {
      path: "/src/App.tsx",
      content: initialApp,
    },
  },
  selectedFilePath: "/src/App.tsx",
  addMessage: (message) =>
    set((state) => ({
      messages: [...state.messages, message],
    })),
  sendMessage: async (prompt) => {
    const content = prompt.trim();
    if (!content) return;

    const userMessage: ChatMessage = {
      id: crypto.randomUUID(),
      role: "user",
      content,
    };

    set((state) => ({
      messages: [...state.messages, userMessage],
      isGenerating: true,
    }));

    await new Promise((resolve) => window.setTimeout(resolve, 2000));

    const aiMessage: ChatMessage = {
      id: crypto.randomUUID(),
      role: "ai",
      content:
        "Entendido! Gerando o código para a sua solicitação e preparando o preview em tempo real...",
    };

    set((state) => ({
      messages: [...state.messages, aiMessage],
      isGenerating: false,
    }));
  },
  setSelectedFilePath: (path) => set({ selectedFilePath: path }),
  upsertFile: (file) =>
    set((state) => ({
      files: {
        ...state.files,
        [file.path]: file,
      },
      selectedFilePath: file.path,
    })),
}));
