import { create } from "zustand";

export type ChatMessage = {
  id: string;
  role: "user" | "ai";
  content: string;
};

type StudioState = {
  messages: ChatMessage[];
  isGenerating: boolean;
  files: Record<string, string>;
  activeFile: string;
  addMessage: (message: ChatMessage) => void;
  sendMessage: (prompt: string) => Promise<void>;
  updateFile: (path: string, content: string) => void;
  setActiveFile: (path: string) => void;
};

const initialApp = `export default function App() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-slate-950 text-3xl font-bold text-white">
      Hello X09 Studio
    </div>
  );
}
`;

const generatedApp = `export default function App() {
  return (
    <main className="min-h-screen bg-slate-950 px-6 py-16 text-white">
      <section className="mx-auto max-w-5xl overflow-hidden rounded-[2rem] border border-violet-400/20 bg-white/10 p-10 shadow-2xl shadow-violet-950/40 backdrop-blur">
        <p className="text-sm font-medium uppercase tracking-[0.28em] text-violet-300">
          Generated by X09 Studio
        </p>
        <div className="mt-10 grid gap-10 md:grid-cols-[1.1fr_0.9fr] md:items-center">
          <div>
            <h1 className="text-5xl font-black tracking-tight md:text-7xl">
              Interface criada em tempo real.
            </h1>
            <p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">
              O X09 recebeu seu prompt, atualizou o sistema de arquivos virtual e sincronizou este preview automaticamente.
            </p>
            <button className="mt-8 rounded-2xl bg-violet-500 px-6 py-3 text-sm font-bold text-white shadow-lg shadow-violet-500/30 transition hover:bg-violet-400">
              Publicar projeto
            </button>
          </div>
          <div className="rounded-[1.5rem] border border-white/10 bg-slate-900 p-5">
            <div className="h-3 w-24 rounded-full bg-emerald-400" />
            <div className="mt-6 space-y-3">
              <div className="h-4 rounded-full bg-white/20" />
              <div className="h-4 w-10/12 rounded-full bg-white/15" />
              <div className="h-4 w-8/12 rounded-full bg-white/10" />
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
`;

const initialPackageJson = `{
  "scripts": {
    "dev": "vite",
    "build": "vite build"
  },
  "dependencies": {
    "@vitejs/plugin-react": "latest",
    "vite": "latest",
    "react": "latest",
    "react-dom": "latest",
    "tailwindcss": "latest"
  },
  "devDependencies": {}
}
`;

export const useStudioStore = create<StudioState>((set) => ({
  messages: [
    {
      id: "welcome",
      role: "ai",
      content:
        "Olá, eu sou o X09. Descreva o sistema que você quer construir e eu preparo a primeira versão.",
    },
  ],
  isGenerating: false,
  files: {
    "/App.tsx": initialApp,
    "/package.json": initialPackageJson,
  },
  activeFile: "/App.tsx",
  addMessage: (message) =>
    set((state) => ({
      messages: [...state.messages, message],
    })),
  sendMessage: async (prompt) => {
    const content = prompt.trim();
    if (!content) return;

    const userMessage: ChatMessage = {
      id: crypto.randomUUID(),
      role: "user",
      content,
    };

    set((state) => ({
      messages: [...state.messages, userMessage],
      isGenerating: true,
    }));

    await new Promise((resolve) => window.setTimeout(resolve, 2000));

    const aiMessage: ChatMessage = {
      id: crypto.randomUUID(),
      role: "ai",
      content:
        "Entendido! Gerando o código para a sua solicitação e preparando o preview em tempo real...",
    };

    set((state) => ({
      messages: [...state.messages, aiMessage],
      files: {
        ...state.files,
        "/App.tsx": generatedApp,
      },
      activeFile: "/App.tsx",
      isGenerating: false,
    }));
  },
  updateFile: (path, content) =>
    set((state) => ({
      files: {
        ...state.files,
        [path]: content,
      },
    })),
  setActiveFile: (path) => set({ activeFile: path }),
}));
